package com.mibsystem.demo.Controllers;

import com.mibsystem.demo.Models.Actors.Alien;
import com.mibsystem.demo.Repository.AlienRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller
@RequestMapping("/Alien")
public class AlienController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private AlienRepository alienRepository;

    @PostMapping(path="/delete/{id}/") // Map ONLY POST Requests
    public @ResponseBody String deleteAlien (@RequestParam int id) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        alienRepository.deleteById(id);
        return "Saved";
    }

    @PostMapping(path="/deleteAll") // Map ONLY POST Requests
    public @ResponseBody void deleteAllAlien () {
        alienRepository.deleteAll();
    }

    @GetMapping(path="/count") // Map ONLY POST Requests
    public @ResponseBody int getCount() {
        return (int) alienRepository.count();
    }


    @GetMapping(path="/all")
    public @ResponseBody Iterable<Alien> getAllAliens() {
        // This returns a JSON or XML with the users
        return alienRepository.findAll();
    }
}